// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWfKuUW2B7RtcSIm5dgoMqGPnNtLrfdY',
    appId: '1:364846661731:web:3044dec142b483a2b8b856',
    messagingSenderId: '364846661731',
    projectId: 'dbapp-f19ee',
    authDomain: 'dbapp-f19ee.firebaseapp.com',
    storageBucket: 'dbapp-f19ee.firebasestorage.app',
    measurementId: 'G-21C6JW4XV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrk0wrPLbusxEx3f5I868iRBRo4PtXIw',
    appId: '1:364846661731:android:6377d40e8398a29ab8b856',
    messagingSenderId: '364846661731',
    projectId: 'dbapp-f19ee',
    storageBucket: 'dbapp-f19ee.firebasestorage.app',
  );
}
