// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqESBLmMVOBatbKRMKP99J-ukK4-4IsA',
    appId: '1:929157236680:web:8c6d0b769c61b0f0b062fd',
    messagingSenderId: '929157236680',
    projectId: 'grimoriaapp',
    authDomain: 'grimoriaapp.firebaseapp.com',
    storageBucket: 'grimoriaapp.firebasestorage.app',
    measurementId: 'G-QB2S89B846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgVmbpmQC5_LhQfrsIuc0wL9VXLgTmN18',
    appId: '1:929157236680:android:068624eac2c45819b062fd',
    messagingSenderId: '929157236680',
    projectId: 'grimoriaapp',
    storageBucket: 'grimoriaapp.firebasestorage.app',
  );
}
